name: 1 - [FEAT] Open PR

on:
  push:
    branches:
      - "feature**"

jobs:
  create_pr_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        shell: bash
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --title "feat: Feature para Develop" --template ".github/PULL_REQUEST_TEMPLATE.md" --base "develop" --draft