name: 1 - [FEAT] PR & Validate

on:
  push:
    branches:
      - "feature**"

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          pr_title: "feat: Feature to Develop"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          pr_reviewer: "leodelmiro"
          pr_draft: true