name: 1 - [FEAT] Open PR

on:
  push:
    branches:
      - "feature**"

jobs:
  create_pr_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "develop"
          title: "feat: Feature para Develop"
          body-path	: ".github/PULL_REQUEST_TEMPLATE.md"
          draft: true