name: 1 - [FEAT] Open PR

on:
  pull_request:
    branches:
      - "develop"

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Format Check
        run: terraform fmt -check -recursive infra/
      - name: Terraform Format
        if: failure()
        run: terraform fmt -recursive infra/

