name: 3 - [DEVELOP] PR & Plan

on:
  pull_request:
    types:
      - "closed"
    branches:
      - "develop"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Terraform Init and Plan
        id: plan
        shell: bash
        run: |
          cd infra
          terraform init
          echo "plan<<EOF" >> "$GITHUB_OUTPUT"
          terraform plan -no-color -out=tfplan >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/tfplan
          overwrite: true
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "feat: Develop to Main"
          pr_template: |
            Terraform Plan:
  
            ```
            ${{ steps.plan.outputs.plan }}
            ```
  
            Plan salvo no GH artifacts.
          pr_draft: true